### ISSUE TITLE
Winning issue

### ISSUE THREAD

**Issue by winniemei** [winniemei/connectFour#1]
Hi guys, 

I am working on putting my detecting win function in my game. It is alerting that I won one turn too late and I've tried putting the function in different areas within my code...Not sure why!!

@WilliamfShaw @DBrodsky90 @pavankat @awongh

**Comment by pavankat** [comment]
Hey Winnie, that's because the check win function isn't being triggered after the fourth click for some reason

Put in break points after the fourth click and check why it's not alerting.
